const RESOURCE_URLS: Record<string, string> = {
  // ── Data skills ──────────────────────────────────────────────────────────
  'fast.ai Practical AI':                    'https://course.fast.ai/',
  'DeepLearning.AI short courses':           'https://www.deeplearning.ai/short-courses/',
  'Anthropic Prompt Engineering Guide':      'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview',
  'dbt Learn':                               'https://learn.getdbt.com/',
  'Apache Airflow docs':                     'https://airflow.apache.org/docs/',
  'DataTalks.Club DE Zoomcamp':              'https://github.com/DataTalksClub/data-engineering-zoomcamp',
  "Python for Data Analysis (O'Reilly)":     'https://wesmckinney.com/book/',
  'Kaggle Learn Python':                     'https://www.kaggle.com/learn/python',
  'Real Python tutorials':                   'https://realpython.com/',
  'AWS Data Analytics Specialty':            'https://aws.amazon.com/certification/certified-data-analytics-specialty/',
  'Google Professional Data Engineer':       'https://cloud.google.com/learn/certification/data-engineer',
  'A Cloud Guru':                            'https://acloudguru.com/',
  'DAMA-DMBOK study guide':                  'https://www.dama.org/cpages/body-of-knowledge',
  'CDMP certification path':                 'https://cdmp.info/',
  'Collibra Academy':                        'https://academy.collibra.com/',
  'Presenting Data and Information (Tufte)': 'https://www.edwardtufte.com/tufte/books_vdqi',
  'Crucial Conversations':                   'https://www.vitalsmarts.com/crucial-conversations-book/',
  'McKinsey comms frameworks':               'https://www.mckinsey.com/featured-insights',
  'Structured Thinking (McKinsey)':          'https://www.mckinsey.com/capabilities/strategy-and-corporate-finance/our-insights',
  'HBR Problem Framing':                     'https://hbr.org/topic/subject/decision-making-and-problem-solving',
  'Minto Pyramid Principle':                 'https://www.barbaraminto.com/',
  'Good Strategy Bad Strategy (Rumelt)':     'https://www.penguinrandomhouse.com/books/208668/good-strategy-bad-strategy-by-richard-rumelt/',
  'HBR Strategy courses':                    'https://online.hbs.edu/subjects/strategy/',
  'Reforge Growth Series':                   'https://www.reforge.com/',
  'Domain-Driven Design (Evans)':            'https://www.oreilly.com/library/view/domain-driven-design-tackling/0321125215/',
  'industry-specific Coursera tracks':       'https://www.coursera.org/',
  'Great Expectations docs':                 'https://docs.greatexpectations.io/',
  'DQMI framework (TDWI)':                   'https://tdwi.org/',
  'Monte Carlo data observability blog':     'https://www.montecarlodata.com/blog/',
  'DataHub documentation':                   'https://datahubproject.io/docs/',
  'Apache Atlas guides':                     'https://atlas.apache.org/',
  'DCAM metadata module':                    'https://edmcouncil.org/frameworks/dcam/',
  'Kimball DW Toolkit':                      'https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/',
  'dbt best practices':                      'https://docs.getdbt.com/best-practices',
  'Databricks Data Modeling course':         'https://www.databricks.com/learn/training',
  'Mode SQL Tutorial':                       'https://mode.com/sql-tutorial/',
  'StrataScratch practice':                  'https://www.stratascratch.com/',
  'Advanced SQL for Data Scientists':        'https://www.oreilly.com/library/view/advanced-sql-for/9781492044888/',
  'Looker LookML docs':                      'https://cloud.google.com/looker/docs/lookml-intro',
  'Tableau Desktop Specialist':              'https://www.tableau.com/learn/certification/desktop-specialist',
  'Power BI DAX deep-dive':                  'https://learn.microsoft.com/en-us/dax/dax-overview',
  'IAPP Privacy Fundamentals':               'https://iapp.org/certify/cipp/',
  'GDPR practitioner guide':                 'https://gdpr.eu/',
  'OneTrust learning hub':                   'https://www.onetrust.com/lp/onetrust-academy/',
  'Storytelling with Data (Knaflic)':        'https://www.storytellingwithdata.com/',
  'Cole Nussbaumer workshops':               'https://www.storytellingwithdata.com/workshops',
  'dataviz.tools':                           'https://dataviz.tools/',

  // ── Software skills ───────────────────────────────────────────────────────
  'Exercism.io practice tracks':             'https://exercism.org/',
  'Crafting Interpreters (Nystrom)':         'https://craftinginterpreters.com/',
  'Language docs + official tour':           'https://roadmap.sh/',
  'Designing Data-Intensive Applications':   'https://dataintensive.net/',
  'ByteByteGo newsletter':                   'https://bytebytego.com/',
  'High Scalability blog':                   'https://highscalability.com/',
  'AWS Solutions Architect Associate':       'https://aws.amazon.com/certification/certified-solutions-architect-associate/',
  'Terraform — HashiCorp Learn':             'https://developer.hashicorp.com/terraform/tutorials',
  'CNCF landscape & certifications':         'https://www.cncf.io/certification/ckad/',
  'Claude Code docs & cookbook':             'https://docs.anthropic.com/en/docs/claude-code/overview',
  'Building LLM Apps (DeepLearning.AI)':    'https://www.deeplearning.ai/short-courses/',
  'xUnit Test Patterns (Meszaros)':          'https://xunitpatterns.com/',
  'Testing JavaScript (Kent C. Dodds)':      'https://testingjavascript.com/',
  'Google Testing Blog':                     'https://testing.googleblog.com/',
  'OWASP Top 10 guide':                      'https://owasp.org/www-project-top-ten/',
  "Web Application Hacker's Handbook":       'https://www.oreilly.com/library/view/the-web-application/9781118026472/',
  'SANS Security courses':                   'https://www.sans.org/',
  "Competitive Programmer's Handbook":       'https://cses.fi/book/book.pdf',
  'NeetCode 150 (curated)':                  'https://neetcode.io/',
  'Algorithm Design (Kleinberg)':            'https://www.pearson.com/en-us/subject-catalog/p/algorithm-design/P200000003504',
  'Use The Index, Luke (SQL tuning)':        'https://use-the-index-luke.com/',
  'CMU Database Systems course':             'https://15445.courses.cs.cmu.edu/',
  'MongoDB University':                      'https://learn.mongodb.com/',
  'The DevOps Handbook':                     'https://itrevolution.com/product/the-devops-handbook/',
  'GitHub Actions docs':                     'https://docs.github.com/en/actions',
  'Continuous Delivery (Humble & Farley)':   'https://continuousdelivery.com/',
  'API Design Patterns (Lochmann)':          'https://www.manning.com/books/api-design-patterns',
  'REST API Design Rulebook':                'https://www.oreilly.com/library/view/rest-api-design/9781449317904/',
  'Stripe API docs (as reference)':          'https://stripe.com/docs/api',
  'High Performance Browser Networking':     'https://hpbn.co/',
  'Systems Performance (Gregg)':             'https://www.brendangregg.com/systems-performance-2nd-edition-book.html',
  'Netflix Tech Blog':                       'https://netflixtechblog.com/',
  'Fundamentals of Software Architecture (Richards)': 'https://www.oreilly.com/library/view/fundamentals-of-software/9781492043447/',
  'Clean Architecture (Martin)':             'https://www.oreilly.com/library/view/clean-architecture-a/9780134494272/',
  'thoughtworks.com/radar':                  'https://www.thoughtworks.com/radar',
  'The Art of Readable Code':                'https://www.oreilly.com/library/view/the-art-of/9781449318482/',
  'Google Engineering Practices Guide':      'https://google.github.io/eng-practices/',
  'LeadDev conference talks':                'https://leaddev.com/',
  'Shape Up (Basecamp)':                     'https://basecamp.com/shapeup',
  'Inspired (Cagan)':                        'https://www.svpg.com/inspired-how-to-create-products-customers-love/',
  'Continuous Discovery Habits (Torres)':    'https://www.producttalk.org/2021/08/product-discovery/',
  'Writing Is Designing (Ames)':             'https://www.writingisdesigning.com/',
  'The Pyramid Principle (Minto)':           'https://www.barbaraminto.com/',
  'AWS Architecture blog (writing model)':   'https://aws.amazon.com/blogs/architecture/',
  'Staff Engineer (Larson)':                 'https://staffeng.com/book',
  'An Elegant Puzzle (Lethain)':             'https://lethain.com/elegant-puzzle/',
}

export function resolveUrl(resourceName: string): string {
  return RESOURCE_URLS[resourceName]
    ?? `https://www.google.com/search?q=${encodeURIComponent(resourceName)}`
}

export default RESOURCE_URLS
